# SPDX-License-Identifier: AGPL-3.0-or-later

[Config]
MinimumVersion=25.3

[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64
RepositoryKeyCheck=yes

[Output]
Format=disk
Output=carbideos
OutputDirectory=mkosi.output
ImageId=carbideos
CompressOutput=zstd
CompressLevel=15
SplitArtifacts=uki,partitions
ManifestFormat=json

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=yes
UnifiedKernelImageFormat=carbideos_%v
Hostname=carbideos
Locale=C.UTF-8
Timezone=UTC
WithDocs=no
WithRecommends=no
CleanPackageMetadata=yes
SELinuxRelabel=yes
Packages=
        basesystem
        bash
        btrfs-progs
        checkpolicy
        cryptsetup
        dbus-broker
        fastfetch
        git-core
        gnupg2
        iproute
        kernel-core
        openssh-server
        qemu-guest-agent
        selinux-policy-targeted
        sudo
        systemd
        systemd-boot
        systemd-container
        systemd-networkd
        systemd-pam
        systemd-resolved
        systemd-udev
        tpm2-tss
        unzip
        util-linux
        zip
RemoveFiles=
        /usr/bin/checkmodule
        /usr/bin/checkpolicy
KernelCommandLine=
        console=tty0
        enforcing=1
        init_on_alloc=1
        init_on_free=1
        lockdown=integrity
        loglevel=3
        module.sig_enforce=1
        oops=panic
        panic=30
        page_alloc.shuffle=1
        randomize_kstack_offset=on
        rd.systemd.show_status=yes
        rd.udev.log_level=err
        security=selinux
        selinux=1
        slab_nomerge
        systemd.show_status=yes
        udev.log_level=err
        vsyscall=none

[Validation]
SecureBoot=yes
SecureBootAutoEnroll=yes
SecureBootKey=keys/secureboot/secure-boot.key
SecureBootCertificate=keys/secureboot/secure-boot.crt
Verity=yes
VerityKey=keys/verity/verity.key
VerityCertificate=keys/verity/verity.crt
SignExpectedPcr=no
Checksum=no
Sign=no

[Build]
ToolsTree=default
ExtraSearchPaths=scripts/compression
CacheDirectory=mkosi.cache
PackageCacheDirectory=mkosi.pkgcache
History=yes

[Runtime]
Firmware=uefi-secure-boot
Console=native
RAM=2G
CPUs=2
