#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

install -d -m 0700 /var/lib/ssh
ssh-keygen -q -t ed25519 -N '' -C '' -f /var/lib/ssh/ssh_host_ed25519_key
ssh-keygen -q -t rsa -b 3072 -N '' -C '' -f /var/lib/ssh/ssh_host_rsa_key
chmod 0600 /var/lib/ssh/ssh_host_ed25519_key /var/lib/ssh/ssh_host_rsa_key
chmod 0644 /var/lib/ssh/ssh_host_ed25519_key.pub /var/lib/ssh/ssh_host_rsa_key.pub
chcon -t sshd_key_t /var/lib/ssh/ssh_host_*_key*
