# SPDX-License-Identifier: AGPL-3.0-or-later

[Partition]
Type=root
Format=erofs
Label=%M_%A_root
CopyFiles=/
ExcludeFilesTarget=/boot/
ExcludeFilesTarget=/efi/
Verity=data
VerityMatchKey=root
SizeMinBytes=768M
SizeMaxBytes=768M
ReadOnly=yes
