# SPDX-License-Identifier: AGPL-3.0-or-later

HostKey /var/lib/ssh/ssh_host_ed25519_key
HostKey /var/lib/ssh/ssh_host_rsa_key
AuthorizedKeysFile /usr/lib/carbideos/authorized_keys/%u
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
AuthenticationMethods publickey
PermitEmptyPasswords no
AllowUsers ace-mgmt
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
GatewayPorts no
MaxAuthTries 3
LoginGraceTime 30
